version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:823104559115:secret:docker-hub-0HdsdW:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:823104559115:secret:docker-hub-0HdsdW:password

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 823104559115.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo t19871027 | docker login -u tsuyoshitakezawa --password-stdin
  build:
    commands:
      - echo Building the nginx Docker image...
      - docker build -t nginx -f nginx/ecs_Dockerfile .
      - docker tag nginx:latest 823104559115.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest

      - echo Building the python Docker image...
      - docker build -t python -f nginx/ecs_Dockerfile .
      - docker tag python:latest 823104559115.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest
  post_build:
    commands:
      - echo Pushing the nginx Docker image...
      - docker push 823104559115.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
      - echo complete to push nginx...

      - echo Pushing the python Docker image...
      - docker push 823104559115.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest
      - echo complete to push python...

      # - cat example_task_definitions.json | sed -e "s@<IMAGE_NGINX_NAME>@823104559115.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest@g" -e "s@<IMAGE_PYTHON_NAME>@{AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest@g" > taskdef.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
